version: '3.7'

services:
  redis:
    image: redis
    ports:
      - 6379:6379
#
#  rabbitmq:
#    image: rabbitmq:3.10.7-management
#    environment:
#      - RABBITMQ_DEFAULT_USER=user
#      - RABBITMQ_DEFAULT_PASS=user
#    ports:
#      - 15672:15672
#      - 5672:5672

