FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt requirements.txt

COPY ./examples/haproxy/server /app

RUN apt update
RUN apt install -y git
RUN apt-get install -y g++
RUN apt install -y python3-pip
RUN pip install --upgrade pip

RUN pip install -r requirements.txt

EXPOSE 5010

ENTRYPOINT ["python", "run.py"]

