version: '3.7'

services:
  haproxy:
    image: haproxy
    ports:
      - 8080:80
      - 8404:8404
      - 8405:8405

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
       - grafana_data:/var/lib/grafana

  web1:
    image: nginx

  web2:
    image: nginx

  web3:
    image: nginx

volumes:
  prometheus_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./prometheus_data
  grafana_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./grafana_data